### ISSUE TITLE
Error: Missing decryptionCert while generating metadata for decrypting service provider

### ISSUE THREAD

**Issue by Akka-P** [italia/spid-passport#11]
Hi, I tried to run it. I used example at bottom of readme, but it responds to me this error... How can I resolve? Thanks
-
Salve, ho provato a fare la run, utilizzando l'esempio sopra. Purtroppo mi risponde quest'errore... Come posso risolverlo? Grazie

```
C:\nodejs\node_modules>node login.js
C:\nodejs\node_modules\spid-passport\index.js:161
      throw new Error(
      ^

Error: Missing decryptionCert while generating metadata for decrypting service provider
    at SpidStrategy.generateServiceProviderMetadata (C:\nodejs\node_modules\spid-passport\index.js:161:13)
    at Object.<anonymous> (C:\nodejs\node_modules\login.js:66:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

C:\nodejs\node_modules>
```

**Comment by MrMavin** [comment]
@Akka-P non potrò essere molto prolisso per mancanza di tempo.

In poche parole dal sorgente questo metodo non fa altro che generare un file `.xml` di metadati.

Un esempio di questo file da un provider certificato (aruba): [https://loginspid.aruba.it/metadata](https://loginspid.aruba.it/metadata)

Perciò nel caso in cui stessi utilizzando `spid-testenv2` ciò che bisogna passare come parametro sarà la chiave pubblica per dargli indicazioni sui parametri `signing` ed `encryption` del file dei metadati.

` 
const metadataFile = spidStrategy.generateServiceProviderMetadata(fs.readFileSync("./conf/idp.crt", "utf-8"));
`

Posso anche dedurre che puoi evitare di utilizzare questo metodo, prendendo direttamente il tuo `sp_metadata.xml` modificato a mano e preso come punto di partenza da quello fornito dal pacchetto `spid-testenv2`
